# MIT License
#
# (C) Copyright [2021] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

version: '3.7'
#THIS environment sets up HSM for locking package testing.
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (red fish sims) are setup and active.
#  The ports are exposed to the local system.
networks:
  rez:
services:
#  etcd:
#    image: arti.dev.cray.com/third-party-docker-stable-local/coreos/etcd:v3.4.7
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
#      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
#    ports:
#      - 2379:2379
#      - 2380:2380
#    networks:
#      - rez
#  s3:
#    image: arti.dev.cray.com/third-party-docker-stable-local/minio/minio:RELEASE.2020-04-10T03-34-42Z
#    hostname: s3
#    environment:
#      MINIO_ACCESS_KEY: s3-access-key
#      MINIO_SECRET_KEY: s3-secret-key
#    command: server /data
#    ports:
#      - "9000:9000"
#    networks:
#      - rez
#  s3-init:
#    image: arti.dev.cray.com/third-party-docker-stable-local/minio/mc:latest
#    hostname: s3-init
#    environment:
#      - MC_HOST_S3=http://s3-access-key:s3-secret-key@s3:9000
#    command: mb S3/fw-update
#    depends_on:
#      - s3
#    networks:
#      - rez
  vault:
    hostname: vault
    image: arti.dev.cray.com/third-party-docker-stable-local/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - rez
  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.13.4
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - rez
  redis:
    image: arti.dev.cray.com/third-party-docker-stable-local/redis:5.0-alpine3.12
    hostname: hms-redfish-redis
    ports:
      - "6379:6379"
    networks:
      - rez
  hmsds-postgres:
    hostname: hmsds-postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "5432:5432"
    networks:
      - rez
  cray-smd-init:
    build:
      context: .
      dockerfile: Dockerfile.smd
    command: [ "smd-init" ]
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      - SMD_DBHOST=hmsds-postgres
    volumes:
      - /persistent_migrations
    depends_on:
      - hmsds-postgres
    networks:
      - rez
  cray-smd:
    build:
      context: .
      dockerfile: Dockerfile.smd
    #image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.29.12
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"
    networks:
      - rez
  zookeeper:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rez
  kafka:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - rez
  cray-hms-hmcollector:
    image: artifactory.algol60.net/csm-docker/stable/hms-hmcollector:2.11.3
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    networks:
      - rez
  redfish-simulator:
    image: artifactory.algol60.net/csm-docker/stable/hms-redfish-translation-service:1.12.5
    environment:
      - SCHEMA_VERSION=2019.1
      - LOG_LEVEL=TRACE
      - PRIVILEGE_REGISTRY_VERSION=1.0.4
      - SCRIPT_DIR_PREFIX=/tmp/redfish
      - VAULT_TOKEN=hms
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - VAULT_ADDR=http://vault:8200
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - HTTPS_CERT=configs/rts.crt
      - HTTPS_KEY=configs/rts.key
      - BACKEND_HELPER=RFSimulator
      - PERIODIC_SLEEP=120
      - COLLECTOR_URL=http://cray-hms-hmcollector
      - HSM_URL=http://cray-smd:27779
      - HMS_VAULT_KEYPATH=hms-creds
      - RF_USERNAME=root
      - RF_PASSWORD=********
      - RF_SIMULATOR_XNAMES=x0c0s1b0,x0c0s2b0
      - LOGLEVEL=4
    ports:
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - redis
      - vault
      - cray-smd
    networks:
      rez:
        aliases:
          - x0c0s1b0
          - x0c0s2b0
