version: '3'
services:
  hmsds-postgres:
    hostname: hmsds-postgres
    image: dtr.dev.cray.com/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "5432:5432"
  cray-smd-init:
    build:
      context: .
      dockerfile: Dockerfile.smd
    command: ["smd-init"]
    entrypoint: ["/entrypoint.sh"]
    environment:
      - SMD_DBHOST=hmsds-postgres
    depends_on:
      - hmsds-postgres
    volumes:
      - /persistent_migrations
  vault:
    hostname: vault
    image: dtr.dev.cray.com/library/vault:1.4.2
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
  cray-smd:
    build:
      context: .
      dockerfile: Dockerfile.smd
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"
