version: '3.7'

networks:
  smd:

services:
  wait-for-smd:
    build:
      context: test/ct/
      dockerfile: Dockerfile.wait-for-smd.Dockerfile
    depends_on:
      - cray-smd
      - cray-hms-hmcollector
      - cray-hmnfd
      - vault-kv-enabler
      - emulator-loader
    networks:
      - smd
  tavern-tests:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    depends_on:
      - cray-smd
    entrypoint: entrypoint.sh tavern -c /src/app/tavern_global_config_ct_test.yaml -p /src/app/api
    networks:
      - smd
  smoke-tests:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    depends_on:
      - cray-smd
    entrypoint: entrypoint.sh smoke -f smoke.json -u http://cray-smd:27779
    networks:
      - smd
  etcd:
    image: artifactory.algol60.net/quay.io/coreos/etcd:v3.4.7
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - smd
  vault:
    hostname: vault
    image: artifactory.algol60.net/docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    networks:
      - smd
  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.18.0
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - smd
  #
  # SLS
  #
  cray-sls-postgres:
    hostname: sls-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "54321:5432"
    networks:
      - smd
  cray-sls-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-sls:2.3.0
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - cray-sls-postgres
    networks:
      - smd
  cray-sls:
    image: artifactory.algol60.net/csm-docker/stable/cray-sls:2.3.0
    environment:
      - POSTGRES_HOST=cray-sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=secret/hms-creds
    ports:
      - "8376:8376"
    depends_on:
      - cray-sls-postgres
      - cray-sls-init
    networks:
      - smd

  #
  # HSM
  #
  hmsds-postgres:
    hostname: hmsds-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    networks:
      - smd
  cray-smd-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: /entrypoint.sh smd-init
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    networks:
      - smd
  cray-smd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
      - SMD_SLS_HOST=http://cray-sls:8376/v1
      - SMD_HBTD_HOST=
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
      - cray-sls
    networks:
      - smd
    ports:
      - "27779:27779"
  zookeeper:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - smd
  kafka:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - smd
  cray-hms-hmcollector:
    image: artifactory.algol60.net/csm-docker/stable/hms-hmcollector:2.20.0
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    networks:
      - smd
    depends_on:
      - kafka
  cray-hmnfd:
    hostname: cray-hmnfd
    image: artifactory.algol60.net/csm-docker/stable/cray-hmnfd:1.17.0
    environment:
      - DEBUG=0
      - SM_URL=http://cray-smd:27779/hsm/v2
      - INBOUND_SCN_URL=https://cray-hmnfd:28600/hmi/v1/scn
      - SM_RETRIES=3
      - SM_TIMEOUT=10
      - PORT=28600
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - TELEMETRY_HOST=kafka:9092:cray-hmsstatechange-notifications
    depends_on:
      - kafka
      - etcd
    networks:
      - smd
  emulator-loader:
    image: artifactory.algol60.net/docker.io/library/golang:1.16-alpine
    command: >
      sh -c "apk add curl && sleep 10 &&
      curl -X POST -d '{\"RedfishEndpoints\":[{
        \"ID\":\"x0c0s1b0\",
        \"FQDN\":\"x0c0s1b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0s2b0\",
        \"FQDN\":\"x0c0s2b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0s3b0\",
        \"FQDN\":\"x0c0s3b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0s4b0\",
        \"FQDN\":\"x0c0s4b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      }]}' http://cray-smd:27779/hsm/v2/Inventory/RedfishEndpoints"
    depends_on:
      - cray-smd
      - rfemulator0
      - rfemulator1
      - rfemulator2
      - rfemulator3
    networks:
      - smd
  rfemulator0:
    hostname: x0c0s1b0
    image: artifactory.algol60.net/csm-docker/stable/csm-rie:1.3.0
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s1b0
      - PORT=443
    networks:
      smd:
        aliases:
          - x0c0s1b0
  rfemulator1:
    hostname: x0c0s2b0
    image: artifactory.algol60.net/csm-docker/stable/csm-rie:1.3.0
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s2b0
      - PORT=443
    networks:
      smd:
        aliases:
          - x0c0s2b0
  rfemulator2:
    hostname: x0c0s3b0
    image: artifactory.algol60.net/csm-docker/stable/csm-rie:1.3.0
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s3b0
      - PORT=443
    networks:
      smd:
        aliases:
          - x0c0s3b0
  rfemulator3:
    hostname: x0c0s4b0
    image: artifactory.algol60.net/csm-docker/stable/csm-rie:1.3.0
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s4b0
      - PORT=443
    networks:
      smd:
        aliases:
          - x0c0s4b0