name: Build PR with goreleaser

on:
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened, edited]
    workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install musl and cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl musl-dev
          sudo apt-get install -y gcc-aarch64-linux-gnu
          sudo apt-get install -y g++-aarch64-linux-gnu
          sudo apt-get install -y gcc-x86-64-linux-gnu
          sudo apt-get install -y g++-x86-64-linux-gnu
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y binfmt-support
          sudo update-binfmts --enable qemu-aarch64
          sudo update-binfmts --display qemu-aarch64
          sudo update-binfmts --enable qemu-arm
          sudo update-binfmts --display qemu-arm
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 1
          fetch-depth: 1
          
      # Set environment variables required by GoReleaser
      - name: Set build environment variables
        run: |
          echo "GIT_STATE=$(if git diff-index --quiet HEAD --; then echo 'clean'; else echo 'dirty'; fi)" >> $GITHUB_ENV
          echo "BUILD_HOST=$(hostname)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV
          echo "BUILD_USER=$(whoami)" >> $GITHUB_ENV

      - name: Build with goreleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          version: '~> v2'
          args: build --clean --snapshot
        id: goreleaser